Qt: Fix long URLs showing the end instead of domain
LadybirdBrowser/ladybird pull request #1097
Opened 2024-08-17 00:32 UTC by Sidicer

Cursor in `LocationEdit` (Address bar) did not return to front after loading - because of that long URLs would hide the domain (location).

![image](https://github.com/user-attachments/assets/07ccbcf4-600e-43c9-9f39-594d59efd6f7)

`SetCursorPosition()` needed two calls as with only one in `highlight_location` block it would still default to the end after load.

2024-08-17 00:56 UTC, jamierocks requested changes
These changes work for me :^)

<details>
<summary>Working Screenshot</summary>
<img src="https://github.com/user-attachments/assets/4368fe32-ed21-46aa-b2e7-70899b9adfcc"/>
</details>

The commit name isn't standard though, the prefix you're looking for is `Ladybird/Qt: ` or some contributors have started to use `UI/Qt: `.

2024-08-17 16:38 UTC, tcl3 commented
This works nicely :)

You also need to update your commit message to use the correct prefix. You can do this using `git commit --amend`.

2024-08-20 14:54 UTC, circl-lastname commented
Please squash the two commits

2024-08-20 15:52 UTC, Sidicer commented
> Please squash the two commits, if that doesn't work try resetting to the previous commit and rewording it

I merged in changes from master between both of the commits, so both squashing and resetting - added all of the merged in changes as well. Do you feel that closing this pull and removing the branch to start over with single correct commit would be the best, to keep good clean git history in `ladybird` ?

2024-08-20 16:04 UTC, circl-lastname commented
Please use `git rebase` instead of `git merge` for the future. Uou can try resetting to the first commit in the PR and running `git rebase master` to be up to date tieh master.

2024-08-20 18:51 UTC, tcl3 approved these changes
Thanks!

2024-08-20 18:51 UTC, merged