LibWeb: rename 'cross-origin opener policy' to 'opener policy'
LadybirdBrowser/ladybird pull request #1399
Opened 2024-09-14 14:36 UTC by 0xkon1

Fix for Issue #1387

2024-09-18 14:01 UTC, AtkinsSJ requested changes
Thanks for doing this!

I've marked a few places where your changes don't quite match the spec text. We're quite fussy about that. :^)

Also in two places the spec still says "cross-origin opener policy". That seems to be a mistake in the spec so while I've noted them, you can ignore them. I've opened https://github.com/whatwg/html/pull/10631 to fix the spec.

When making corrections, please make the changes to your existing commit. [This video](https://www.youtube.com/watch?v=ElRzTuYln0M) is good at explaining how to do that in case you're not super familiar with git. You can also ask here or on Discord if you get confused.

2024-09-18 14:40 UTC, AtkinsSJ commented on Userland/Libraries/LibWeb/HTML/Navigable.cpp
> +    // 14. Let coop be targetNavigable's active document's opener policy.
This has been corrected now.

2024-09-18 17:53 UTC, 0xkon1 commented
Thank you for the feedback. I could have done it easier by just copying the spec text. Should al be corrected now.

2024-09-24 11:30 UTC, AtkinsSJ approved these changes
Looks good! Thanks again. :^)

2024-09-24 11:30 UTC, merged

2024-09-24 11:33 UTC, 0xkon1 commented
Happy to be able to contribute! Thanks for the help.
\