LibJS: implement MakeConstructor
LadybirdBrowser/ladybird pull request #1503
Opened 2024-09-23 18:00 UTC by mobounya

Implement "10.2.5 MakeConstructor" in the ecma262 specs https://tc39.es/ecma262/#sec-makeconstructor

2024-09-23 18:34 UTC, ADKaster requested changes

2024-09-23 18:34 UTC, ADKaster commented on Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
> +void ECMAScriptFunctionObject::make_constructor(bool writable_prototype, Object* prototype)
the signature here should be `make_constructor(GCPtr<Object> prototype = nullptr)` instead of passing two arguments, one of which is a raw pointer.

2024-09-23 18:34 UTC, ADKaster commented on Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
> +    // taken care of by default argument value
`bool writeable_prototype = (prototype == nullptr);`

2024-09-23 18:34 UTC, ADKaster commented on Userland/Libraries/LibJS/Runtime/ECMAScriptFunctionObject.cpp
> +        prototype = Object::create(*m_realm, prototype);
This call is `prototype = Object::create(*m_realm, nullptr);`

The spec is asking for `prototype = Object::create(*m_realm, m_realm->intrinsics().object_prototype());`

2024-09-23 18:34 UTC, ADKaster commented on Userland/Libraries/LibJS/Runtime/Object.h
> +    Object* prototype() { return shape().prototype(); }
this visibility change seems unnecessary?

2024-09-27 16:08 UTC, mobounya commented
this took a different turn, so I will open a new PR with a new branch.

2024-09-27 16:08 UTC, closed without merging