LibJS: Do not print lage arrays
LadybirdBrowser/ladybird pull request #1705
Opened 2024-10-09 21:38 UTC by DasBasti

Printing the whole array causes wpt [console/console-log-large-array.any.html](https://wpt.fyi/results/console/console-log-large-array.any.html?product=ladybird) to crash. 
This limits logged arrays to 100 elements and truncates the rest with ...
The runtime of the test on my machine went from 25 seconds down to 7.

The 100 is an arbitrary selected number so if you have a better solution I am happy to change it.

2024-10-10 08:32 UTC, AtkinsSJ commented
> Also, printing a large array probably shouldn't crash, have you looked into the cause of it?

The test logs an array with 10 million elements. (Well, actually 2 arrays with 10 million elements each.) Some kind of truncation is necessary. :sweat_smile: Firefox and Chrome both divide the output up into expandable chunks so you still can theoretically view each element, but it doesn't try to dump everything out at once.

![image](https://github.com/user-attachments/assets/99e27617-9f1f-40a5-99b7-afaa519ad2bb)

That seems like the best option but it's also not possible without implementing some kind of lazy-loading. IMO, this is a reasonable solution for now.

2024-10-10 08:36 UTC, Hendiadyoin1 commented
Note for the future:
Printing, and lazy printing are observable on some objects
See #1112

2024-10-10 08:37 UTC, AtkinsSJ requested changes
Not crashing is good!

As circl mentioned, there's a typo in the commit title. But also, you seem to have stumbled across a loophole in our commit linter. :sweat_smile: Lines in the commit description should be wrapped at 72 characters. There's an exception for URLs, so I think the `console/console-log-large-array.any.html` part tricked it!

2024-10-10 08:37 UTC, AtkinsSJ commented on Userland/Libraries/LibJS/Print.cpp
> +    size_t cnt = 0;
We like to use descriptive variable names, something like `printed_count` would be better. (See [CodingStyle.md](https://github.com/LadybirdBrowser/ladybird/blob/master/Documentation/CodingStyle.md))

2024-10-10 08:37 UTC, AtkinsSJ commented on Userland/Libraries/LibJS/Print.cpp
> +        size_t cnt = 0;                                                                  \
...same here.

2024-10-11 08:59 UTC, AtkinsSJ approved these changes
Looks good to me! Thanks :^)

2024-10-11 08:59 UTC, merged