LibWeb: Strip tabs before text shaping
LadybirdBrowser/ladybird pull request #1912
Opened 2024-10-22 13:13 UTC by kostyafarber

Handling tabs during text shaping caused issues because we tried to index 'input_glyph_info' whilst iterating until 'glyph_count' and these can be different sizes.

The difference is due to when one or more characters get merged into the same glyph when calling 'input_glyph_info' (see https://lazka.github.io/pgi-docs/HarfBuzz-0.0/classes/glyph_info_t.html).

We don't want to render tabs as they come up as tofu characters so instead let's strip them out of the text chunk before starting text shaping.

2024-10-22 13:14 UTC, kostyafarber commented
Have checked with @tcl3 that this change doesn't re-create the crash he experienced on his machine, but want to check with @BenWiederhake that this commit doesn't crash that Wikipedia page he was talking about.

2024-10-22 15:02 UTC, kalenikaliaksandr requested changes
could you add a test for this change?

2024-10-22 18:51 UTC, kostyafarber commented
@kalenikaliaksandr this might be hard to do as we would need to load user fonts to trigger this crash and the layout tests don't currently do this

2024-10-22 19:42 UTC, merged

2024-10-24 19:25 UTC, BenWiederhake commented
No longer crashes. Hooray!