Fix paths in tests
LadybirdBrowser/ladybird pull request #2216
Opened 2024-11-07 21:10 UTC by shlyakpavel

Each commit addresses a test or a set of test that caused "file not found" errors unintentionally

2024-11-07 21:20 UTC, shlyakpavel commented
Also, 

- [ ] Text/input/wpt-import/css/selectors/focus-visible-009.html cannot find utils.js
- [ ] Text/input/wpt-import/css/selectors/focus-visible-017-2.html cannot find green.png

2024-11-07 21:57 UTC, AtkinsSJ commented
Did you fix these manually or delete them and run the importer again? I made the importer a bit smarter recently but if there are still things it misses it'd be good to know.

2024-11-07 21:59 UTC, shlyakpavel commented
@AtkinsSJ I tried deleting and reimporting, but that didn't help me, so I had to do it manually. Also, some of the tests I fixed here are actually not WPT tests.

2024-11-08 09:38 UTC, shlyakpavel commented
Rebased to fix CI

2024-11-08 10:20 UTC, shlyakpavel commented
CI failure is still totally unrelated to the issue, timing out just like it does on other branches and PRs

2024-11-11 12:29 UTC, AtkinsSJ requested changes
The first two commits don't affect the test results at all, what's happening with those?

2024-11-11 12:29 UTC, AtkinsSJ commented on Tests/LibWeb/Layout/input/input-text-to-image.html
> +<input type="text" src="../../../LibWeb/Assets/120.png" width="120" height="120" />
You can drop the `../LibWeb/` from this, we're already in `LibWeb`

2024-11-11 12:29 UTC, AtkinsSJ commented on Tests/LibWeb/Text/input/wpt-import/css/css-grid/alignment/grid-alignment-implies-size-change-011.html
> +  <img id="item" src="../../css-flexbox/support/100x100-green.png"></img>
This isn't the correct URL. The tests on wpt.live are linking to `https://wpt.live/css/css-grid/alignment/support/100x100-green.png`. The real issue seems to be that we don't have that file downloaded.

2024-11-11 17:28 UTC, shlyakpavel commented
Maybe I should just wait for https://github.com/LadybirdBrowser/ladybird/issues/2282

2024-11-27 20:09 UTC, shlyakpavel commented
> The first two commits don't affect the test results at all, what's happening with those?

That's ok, we just don't pass them. Now there's no 404 in the log, so this is a small step towards these tests passing in the future when related implementation improves in Ladybird

2024-11-27 20:16 UTC, shlyakpavel commented
Since I made these PR, these tests introduced new File not founds:
- A lot of tests under Tests/LibWeb/Text/input/wpt-import/html/webappapis/dynamic-markup-insertion/document-write
- Text/input/wpt-import/html/dom/aria-attribute-reflection.html
- Text/input/wpt-import/dom/events/Event-constants.html (it's main js file lol)
- Text/input/wpt-import/custom-elements/upgrading.html

This spreads like a virus...

2024-11-27 20:28 UTC, shlyakpavel commented
Whoever reviews this, please just run 
`./Meta/ladybird.sh run headless-browser -R Tests/LibWeb -j1`
and compare the before/after for yourself

2024-11-29 12:16 UTC, AtkinsSJ approved these changes
Thanks for this!

2024-11-29 12:16 UTC, merged