Fix svg foreign object crash
LadybirdBrowser/ladybird pull request #2381
Opened 2024-11-16 13:44 UTC by Psychpsyo

This makes it so that ``<foreignObject>``s no longer crash the SVG renderer.
This used to crash but now doesn't:
```html
<!DOCTYPE html>
<svg>
	<foreignObject width="160" height="160">
		<span>foo</span>
	</foreignObject>
</svg>
```

A page that is fixed by this is https://battle.crossuniverse.net/game/index.html

This just renders any non-SVG paintable inside an SVG as a new stacking context.
I'm not sure if that is 100% right in all cases, but it seems like it might be so I've just added a FIXME for now.

2024-11-16 17:35 UTC, awesomekling commented
Please add the crashing SVG as a test :)

2024-11-16 19:20 UTC, Psychpsyo commented
> Please add the crashing SVG as a test :)

Done :)

2024-11-18 20:15 UTC, shlyakpavel commented
This also fixes crash in https://wpt.fyi/results/svg/geometry/parsing/height-computed.svg?product=ladybird&product=safari%5Bstable%5D&q=ladybird%3Acrash

2024-11-18 22:18 UTC, Psychpsyo commented on Tests/LibWeb/Ref/input/svg-text-crash.html
> +</svg>
Not sure how I typo'd `<foreingObject>` to `<foreignElement>` in that one, but I've fixed it now.

2024-11-18 22:26 UTC, shlyakpavel commented on Tests/LibWeb/Ref/input/svg-text-crash.html
> +</svg>
Yeah, it's good now

2024-11-18 23:07 UTC, kalenikaliaksandr requested changes
the probl

2024-11-18 23:07 UTC, kalenikaliaksandr commented on Libraries/LibWeb/Painting/SVGSVGPaintable.cpp
>      });
so, basically the problem is that we could encounter TextPaintable here and then verify cast will fail. then the fix could be much simpler here:
```diff
--- a/Libraries/LibWeb/Painting/SVGSVGPaintable.cpp
+++ b/Libraries/LibWeb/Painting/SVGSVGPaintable.cpp
@@ -100,8 +100,8 @@ void SVGSVGPaintable::paint_descendants(PaintContext& context, PaintableBox cons
     };

     paintable.before_children_paint(context, PaintPhase::Foreground);
-    paintable.for_each_child([&](auto& child) {
-        paint_svg_box(verify_cast<PaintableBox>(child));
+    paintable.for_each_child_of_type<PaintableBox>([&](PaintableBox& child) {
+        paint_svg_box(child);
         return IterationDecision::Continue;
     });
     paintable.after_children_paint(context, PaintPhase::Foreground);
```
FYI TextPaintable only serves for hit-testing purposes, so it's ok to simply skip it here.

2024-11-19 12:41 UTC, merged