LibWeb: Support content-visibility css + resolve fixme
LadybirdBrowser/ladybird pull request #267
Opened 2024-06-24 10:26 UTC by EdwinHoksberg

2024-06-25 07:58 UTC, AtkinsSJ commented
I'll try and look at this later today. I think I spotted a couple of small issues but I've only had time to look through it on my phone. 😅

2024-06-25 15:07 UTC, AtkinsSJ requested changes

2024-06-27 20:10 UTC, EdwinHoksberg commented on Userland/Libraries/LibWeb/CSS/Properties.json
> +    ]
Neat ✨

2024-06-27 20:12 UTC, EdwinHoksberg commented on Userland/Libraries/LibWeb/Layout/TreeBuilder.cpp
> +        if (display.is_none() || element.has_parent_with_content_visibility_hidden())
That is a lot better yes, I was actually looking for something like that but I totally overlooked that part 😅 Let me know if I implemented it correctly now. 
And yes, pseudo elements should also be invisible, I've added the check there too.

2024-06-27 20:12 UTC, EdwinHoksberg commented on Tests/LibWeb/Layout/input/css-content-visibility.html
> +</style><div><span>I am not visible
Yes, good idea!

2024-07-15 10:55 UTC, AtkinsSJ approved these changes
Looks good, sorry for the delay! I've had a busy couple of weeks. :sweat_smile: 

There's a conflict that needs fixing, but otherwise this should be good to go.

2024-07-19 08:04 UTC, AtkinsSJ approved these changes
Let's gooooo!

2024-07-19 08:04 UTC, merged