MZ-2668: Layout standalone SVG file obeys width/height attributes
LadybirdBrowser/ladybird pull request #2672
Opened 2024-12-01 05:21 UTC by manuel-za

Solves #2668 

- parity with Chromium (131.0.6778.85)
- very close to Firefox (129.0.2) -- difference not material

2024-12-01 11:52 UTC, circl-lastname commented
Could you write "Fixes #2668"? That way Github automatically marks that issue resolved once merged

2024-12-02 15:18 UTC, AtkinsSJ requested changes
Hi, welcome to Ladybird! :^)

A couple of more general comments:
- That first commit adds a test before the commit that makes the test pass. Please move it either into the second commit, or after it - all tests should pass when they're added.
- Commit titles should be imperatives (like a command). So, "Add unit tests..." instead of just "Unit tests...", and "Make standalone SVG files obey width..."

2024-12-02 15:18 UTC, AtkinsSJ commented on Libraries/LibWeb/Layout/SVGFormattingContext.cpp
> +        // DOM::Document::is_xml_document basically means "it is not an html document" (https://dom.spec.whatwg.org/#xml-document)
Looks like for SVG documents we also set the content type, so you should be able to check `content_box().document().content_type() == "image/svg+xml"_string`.

Also, `<svg>` can appear inside another `<svg>`. If you want to only set the width and height for top-level SVGs, you'll need to add a check for that somehow.

2024-12-06 14:55 UTC, manuel-za commented
@AtkinsSJ : Thanks for the comments. Makes sense.
Rather than rewrite history + pollute the log, I created another PR addressing the comments: https://github.com/LadybirdBrowser/ladybird/pull/2806

I believe this new PR addresses your requested changes:
- unit tests come after the code change
- found a reliable way to detect running in the top formatting context

I would appreciate a review. Thanks! :]m

2024-12-06 14:56 UTC, manuel-za commented
...closing and moving to #2806

2024-12-06 14:56 UTC, manuel-za commented
@AtkinsSJ : Thanks for the comments. Makes sense.
Rather than rewrite history + pollute the log, I created another PR addressing the comments: https://github.com/LadybirdBrowser/ladybird/pull/2806

I believe this new PR addresses your requested changes:
- unit tests come after the code change
- found a reliable way to detect running in the top formatting context

I would appreciate a review. Thanks! :]m

2024-12-06 14:56 UTC, closed without merging