LibWeb: Implement multiple import map support
LadybirdBrowser/ladybird pull request #2824
Opened 2024-12-07 11:31 UTC by shannonbooth

2024-12-07 14:34 UTC, shannonbooth commented
(WPT import doesnt work here as those tests rely on the python server thing in the harness)

2024-12-10 10:20 UTC, Lubrsi requested changes
Lokking good, just a couple nitpicks :^)

2024-12-10 10:20 UTC, Lubrsi commented on Libraries/LibWeb/HTML/Scripting/ImportMap.cpp
> +                            MUST(String::formatted("An import map rule for specifier '{}' was ignored as onet was already present in the existing import map", specifier_key)));
nit:
```suggestion
                            MUST(String::formatted("An import map rule for specifier '{}' was ignored as one was already present in the existing import map", specifier_key)));
```

2024-12-10 10:20 UTC, Lubrsi commented on Libraries/LibWeb/HTML/Scripting/ImportMap.cpp
> +                console.output_debug_message(JS::Console::LogLevel::Warn,
praise: I didn't know we could do this, nice alternative to plain dbgln :^)

2024-12-10 10:20 UTC, Lubrsi commented on Libraries/LibWeb/HTML/Window.h
> +    // NOTE: The resolved module set ensures that module specifier resolution returns the same result when called
nit:
```suggestion
    // Spec-Note: The resolved module set ensures that module specifier resolution returns the same result when called
```

2024-12-10 11:01 UTC, Lubrsi approved these changes

2024-12-10 12:01 UTC, merged