LibWeb: Port to Windows
LadybirdBrowser/ladybird pull request #3000
Opened 2024-12-21 07:04 UTC by stasoid

2025-01-16 01:59 UTC, stasoid commented
unstale

2025-02-12 12:34 UTC, ADKaster requested changes
I don't like the AK/Time patch, but the rest looks good.

2025-02-12 12:42 UTC, ADKaster commented on AK/Time.h
> +inline int gettimeofday(struct timeval* tv, struct timezone*)
added to https://github.com/LadybirdBrowser/ladybird/pull/3551

2025-02-12 14:28 UTC, stasoid commented on AK/Time.h
> +inline int gettimeofday(struct timeval* tv, struct timezone*)
Turns out LibWeb no longer uses gettimeofday, so I just removed the Time.h commit.

2025-02-12 23:11 UTC, ADKaster approved these changes
Thanks, I reworded the last commit to be a bit more descriptive. especially since there's more patches required to get LibWeb building and linking.

2025-02-13 01:42 UTC, merged