LibWeb/CSS: WIP
LadybirdBrowser/ladybird pull request #3010
Opened 2024-12-22 19:20 UTC by LucasChollet

Unfortunately, there is no explicit and step-by-step spec to perform the serialization of `color()` declared values, so while being spec-informed, this is quite ad-hoc.

Fixes 81 subtests in:
 - css/css-color/parsing/color-valid-color-function.html

2024-12-22 23:29 UTC, LucasChollet commented
Oops, I forgot to rebase the test.

2025-01-03 11:09 UTC, AtkinsSJ requested changes
Generally good, just nits.

2025-01-03 11:09 UTC, AtkinsSJ commented on Libraries/LibWeb/CSS/StyleValues/CSSColor.cpp
> +            if (is<PercentageStyleValue>(*value))
Use `value->is_percentage()` instead of the `is<>` macro.

2025-01-03 11:09 UTC, AtkinsSJ commented on Libraries/LibWeb/CSS/StyleValues/CSSColor.cpp
> +            if (is<NumberStyleValue>(*alpha))
`is_number()`

2025-01-03 11:09 UTC, AtkinsSJ commented on Libraries/LibWeb/CSS/StyleValues/CSSColor.cpp
> +        if (is<NumberStyleValue>(*alpha) && alpha->as_number().value() < 0)
`is_number()`

2025-01-03 16:49 UTC, AtkinsSJ approved these changes

2025-01-03 16:49 UTC, merged