LibWeb: Harmonize look of range input element
LadybirdBrowser/ladybird pull request #513
Opened 2024-07-08 20:24 UTC by simonkrauter

Previously the entire slider track was colored.
Now only the lower part of the slider track (left side of the thumb) is colored.
Chrome and Firefox do the same.

Implementation note:
I called the new shadow dom element "-moz-range-progress", because I have not found the corresponding name with the "-webkit" prefix.

Screenshot Ladybird before:
![ladybird_before](https://github.com/LadybirdBrowser/ladybird/assets/8593614/35eefeeb-c82c-4a9e-a309-795ca13d6983)

Screenshot Ladybird after:
![ladybird_after](https://github.com/LadybirdBrowser/ladybird/assets/8593614/a3d37c8c-f781-45a9-acc3-ce716f3de6b7)

Screenshot Chrome:
![chrome](https://github.com/LadybirdBrowser/ladybird/assets/8593614/4df975b1-486f-4038-8750-7f68895378e5)

Screenshot Firefox:
![firefox](https://github.com/LadybirdBrowser/ladybird/assets/8593614/de3a4e90-816d-4b85-ba46-a27409f64b52)

2024-07-08 21:22 UTC, simonkrauter commented
Update: Set the length of the blue bar to 0, when the value is NaN.

2024-07-09 06:59 UTC, bplaat commented
Nice work on improving the `input[type=range]`, but it is a bit strange that we no use a `-moz-` pseudo element without supporting all of them. Currently we only support `-webkit-` pseudo elements. We need to think about if we want to support `-moz-` stuff in the future, and what takes priority? For now it seems better to create an internal pseudo element, I think.

2024-07-09 07:02 UTC, bplaat requested changes

2024-07-09 07:02 UTC, bplaat commented on Userland/Libraries/LibWeb/HTML/HTMLInputElement.h
> +    JS::GCPtr<DOM::Element> m_range_progress_element;
You also need to visit this GC item in `HTMLInputElement::visit_edges()`

2024-07-09 15:52 UTC, simonkrauter commented
Update:
- use `-webkit-progress-value` instead of `-moz-range-progress`
- add m_range_progress_element to visit_edges()

2024-07-09 16:13 UTC, bplaat commented
Nice work, small nitpic comment: I don't know if `-webkit-progress-value` is a correct fit, maybe `-libweb-slider-progress` is better. But I'll let the maintainers decide on that.

2024-07-09 16:34 UTC, simonkrauter commented
Oh, now I saw, that `-webkit-progress-value` is meant for the `<progress>` element :(

2024-07-09 17:00 UTC, simonkrauter commented
Update 3:
- Assign the style for the shadow DOM element directly and don't use any pseudo CSS class name

2024-07-09 17:02 UTC, bplaat approved these changes
Haha, looks good to me

2024-07-10 16:59 UTC, ADKaster approved these changes

2024-07-10 16:59 UTC, merged