LibWeb/Fetch: Implement fetch record and fetch group
LadybirdBrowser/ladybird pull request #673
Opened 2024-07-16 18:50 UTC by mobounya

Implement 'fetch records' and 'fetch group' concepts from the fech specs:
https://fetch.spec.whatwg.org/#concept-fetch-record

2024-07-18 09:48 UTC, kalenikaliaksandr requested changes

2024-07-18 09:48 UTC, kalenikaliaksandr commented on Userland/Libraries/LibWeb/Fetch/Infrastructure/FetchRecord.h
> +class FetchRecord : public JS::Cell {
`FetchRecord` needs `visit_edges()` for `m_request` and `m_fetch_controller`

2024-07-18 09:48 UTC, kalenikaliaksandr commented on Userland/Libraries/LibWeb/HTML/Scripting/Environments.h
> +    Vector<JS::NonnullGCPtr<Fetch::Infrastructure::FetchRecord>> m_fetch_group;
`m_fetch_group` needs to be visited by GC.

2024-07-18 11:17 UTC, kennethmyhra reviewed
Added some comments on formatting changes and copyright changes that should be in the first commit.

Maybe `FetchRecord` and `fetch_group()` could each be their own commit and then the implementation of the steps that requires `fetch records` and `fetch group` concepts be in a third commit?

2024-07-18 11:17 UTC, kennethmyhra commented on Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
> +                }
We can visit this
```suggestion
                inflight_keep_alive_bytes += in_flight_request->body().visit(
                    [](Empty) { return 0ul; },
                    [](ByteBuffer const& buffer) {return buffer.size(); },
                    [](JS::NonnullGCPtr<Infrastructure::Body> body) {
                        return body->length().has_value() ? body->length().value() : 0ul;
                    });
```

2024-07-19 08:29 UTC, AtkinsSJ commented
Hi, not a comment on your code, but please click the `[ Resolve conversation ]` button on each review comment after you've pushed changes that resolve that issue. It makes it a lot clearer what is done and what isn't. :^)

2024-07-19 13:30 UTC, kennethmyhra reviewed
Looks good, just a minor nit + wrap the commit text when you exceed 72 characters, now they are arbitrary wrapped between 50-something and 60-something characters.

Also, as Sam pointed out make sure to resolve the comments you have addressed

2024-07-19 19:51 UTC, kennethmyhra approved these changes

2024-07-19 20:05 UTC, kennethmyhra commented
Seems we are breaking macOS CI in the `visit()`, there's a mix of `u64` and `size_t` being returned that seems to cause the breakage. I do not have a Mac to test it out on, but try to put a `static_cast` in the `ByteBuffer` section like shown below (unless someone else comes by that has a better idea).
```cpp
[](ByteBuffer const& buffer) { return static_cast<u64>(buffer.size()); },
```

2024-07-19 20:36 UTC, mobounya commented
macOS CI still fails, I guess someone with access to a Mac should try it. doing a force push and a full build each time seems a bit tedious

2024-07-19 21:13 UTC, ADKaster commented
Given the error 

Users/runner/work/ladybird/ladybird/AK/Variant.h:118:13: error: 'decltype(auto)' in return type deduced as 'unsigned long long' here but deduced as 'unsigned long' in earlier return statement
            return visit<Self, Visitor, CurrentIndex + 1>(self, id, data, forward<Visitor>(visitor));
            ^

Presumably the code you added is making assumptions about the type equivalence of size_t and u64. Or some similar non-portable integer type issue.

2024-07-20 08:32 UTC, kennethmyhra commented on Userland/Libraries/LibWeb/Fetch/Fetching/Fetching.cpp
> +                        return body->length().has_value() ? body->length().value() : 0ul;
Now that you are specifying the return type explicitly for the lambdas it should be safe to remove the type suffixes.

I tested this change for macOS Clang CI in my own fork: https://github.com/kennethmyhra/ladybird/actions/runs/10018680213/job/27694305833?pr=4

```suggestion
                    [](Empty) -> u64 { return 0; },
                    [](ByteBuffer const& buffer) -> u64 { return buffer.size(); },
                    [](JS::NonnullGCPtr<Infrastructure::Body> body) -> u64 {
                        return body->length().has_value() ? body->length().value() : 0;
```

2024-07-20 19:33 UTC, kennethmyhra approved these changes
Thanks, this looks good now!

Apologies for leading you down the path of type deducing in the lambdas.

2024-07-20 20:09 UTC, merged

2024-07-20 20:29 UTC, mobounya commented
> Thanks, this looks good now!
> 
> Apologies for leading you down the path of type deducing in the lambdas.

No problem at all, thanks everyone for the reviews, happy to have my first Ladybird contribution :tada: :tada: