AK: Explicitly check for null data in Utf16View::validate
LadybirdBrowser/ladybird pull request #734
Opened 2024-07-20 11:33 UTC by trflynn89

The underlying CPU-specific instructions for validating UTF-16 strings behave differently for null inputs. Add an explicit check for this state for consistency.

Fixes #727

(@tcl3 or @jamierocks, can you try this patch on wikipedia and the unit test on your machines as well?)

2024-07-20 11:39 UTC, tcl3 approved these changes
I can confirm that this fixes the issue for me, thanks for looking into it!

2024-07-20 11:45 UTC, jamierocks approved these changes
Fixes the issue for me :)

2024-07-20 11:55 UTC, jamierocks requested changes
I've done some browsing with this change, and it seems to have an unintended consequence.

```cpp
ParsedCookie parsed_cookie { MUST(String::from_utf8(name)), MUST(String::from_utf8(value)) };
```

Code like the above now fails when a value is "". A few sites I tested failed - e.g. youtube.com which tried to set the following cookie.

```
32211.160 WebContent(160720): name: VISITOR_INFO1_LIVE
32211.160 WebContent(160720): value:
```

```diff
diff --git a/Userland/Libraries/LibWeb/Cookie/ParsedCookie.cpp b/Userland/Libraries/LibWeb/Cookie/ParsedCookie.cpp
index 67b34d3b70..c07386482a 100644
--- a/Userland/Libraries/LibWeb/Cookie/ParsedCookie.cpp
+++ b/Userland/Libraries/LibWeb/Cookie/ParsedCookie.cpp
@@ -76,6 +76,8 @@ Optional<ParsedCookie> parse_cookie(StringView cookie_string)
         return {};
 
     // 6. The cookie-name is the name string, and the cookie-value is the value string.
+    dbgln("name: {}", name);
+    dbgln("value: {}", value);
     ParsedCookie parsed_cookie { MUST(String::from_utf8(name)), MUST(String::from_utf8(value)) };
 
     parse_attributes(parsed_cookie, unparsed_attributes);
```

2024-07-20 11:59 UTC, trflynn89 commented
Yeah I had dropped the UTF-8 change from this PR, since I found similar issues with it

2024-07-20 12:24 UTC, trflynn89 commented
Drafting this for now, the more I think about it, the more it makes sense to me that `Utf16View {}.to_utf8()` would return an empty string rather than an error

2024-07-21 11:50 UTC, trflynn89 commented
Should be good to go now

2024-07-21 17:57 UTC, merged